// Builds Eidra tokens from DTCG JSON into:
//   dist/eidra-tokens.css  — CSS custom properties (:root primitives + light/dark themes)
//   src/_generated.ts      — typed CSS-variable references for use in code
// Run via `node build.mjs` (wrapped by `pnpm build`, before tsup compiles the TS).
import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const PREFIX = 'eidra';
const BUILD = 'build/';

const val = (t) => t.$value ?? t.value;
const typ = (t) => t.$type ?? t.type;
const isSemantic = (t) => t.filePath.replace(/\\/g, '/').includes('/semantic/');

StyleDictionary.registerTransform({
  name: 'eidra/name',
  type: 'name',
  transform: (token) =>
    [PREFIX, ...token.path.filter((p) => p.toLowerCase() !== 'default')].join('-').toLowerCase(),
});

StyleDictionary.registerTransform({
  name: 'eidra/font-family',
  type: 'value',
  filter: (t) => typ(t) === 'fontFamily',
  transform: (t) => {
    const v = val(t);
    return (Array.isArray(v) ? v : [v]).map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
  },
});

StyleDictionary.registerTransform({
  name: 'eidra/cubic-bezier',
  type: 'value',
  filter: (t) => typ(t) === 'cubicBezier',
  transform: (t) => {
    const v = val(t);
    return Array.isArray(v) ? `cubic-bezier(${v.join(', ')})` : v;
  },
});

StyleDictionary.registerTransformGroup({
  name: 'eidra/css',
  transforms: ['eidra/name', 'eidra/font-family', 'eidra/cubic-bezier'],
});

const camel = (name) =>
  name.replace(/^eidra-/, '').replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

StyleDictionary.registerFormat({
  name: 'eidra/ts',
  format: ({ dictionary }) => {
    const seen = new Set();
    const lines = [];
    for (const t of dictionary.allTokens) {
      const key = camel(t.name);
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(`export const ${key} = "var(--${t.name})" as const;`);
    }
    return `// Generated by build.mjs — do not edit.\n${lines.join('\n')}\n`;
  },
});

// Tailwind v3 preset — maps every --eidra-* token to a Tailwind theme key so
// consuming apps get `bg-eidra-accent`, `p-eidra-4`, `rounded-eidra-lg`, etc.
// Utilities reference the CSS variables, so they stay theme-reactive (light /
// dark / finance). Keyed off the generated var name to mirror it exactly.
StyleDictionary.registerFormat({
  name: 'eidra/tailwind',
  format: ({ dictionary }) => {
    const theme = {
      colors: {},
      spacing: {},
      borderRadius: {},
      boxShadow: {},
      fontFamily: {},
      fontSize: {},
      fontWeight: {},
      lineHeight: {},
      letterSpacing: {},
      zIndex: {},
      transitionDuration: {},
      transitionTimingFunction: {},
    };
    const put = (bucket, key, name) => {
      theme[bucket][`eidra-${key}`] = `var(--${name})`;
    };
    for (const t of dictionary.allTokens) {
      const name = t.name; // e.g. eidra-accent, eidra-space-4, eidra-color-finance-blue
      const s = name.replace(/^eidra-/, '');
      if (typ(t) === 'color') {
        put('colors', s.replace(/^color-/, ''), name);
      } else if (s.startsWith('space-')) {
        put('spacing', s.slice('space-'.length), name);
      } else if (s.startsWith('size-')) {
        put('spacing', s.slice('size-'.length), name);
      } else if (s.startsWith('radius-')) {
        put('borderRadius', s.slice('radius-'.length), name);
      } else if (s.startsWith('shadow-')) {
        put('boxShadow', s.slice('shadow-'.length), name);
      } else if (s.startsWith('z-')) {
        put('zIndex', s.slice('z-'.length), name);
      } else if (s.startsWith('duration-')) {
        put('transitionDuration', s.slice('duration-'.length), name);
      } else if (s.startsWith('easing-')) {
        put('transitionTimingFunction', s.slice('easing-'.length), name);
      } else if (s.startsWith('font-family-')) {
        put('fontFamily', s.slice('font-family-'.length), name);
      } else if (s.startsWith('font-size-')) {
        put('fontSize', s.slice('font-size-'.length), name);
      } else if (s.startsWith('font-weight-')) {
        put('fontWeight', s.slice('font-weight-'.length), name);
      } else if (s.startsWith('font-line-height-')) {
        put('lineHeight', s.slice('font-line-height-'.length), name);
      } else if (s.startsWith('font-letter-spacing-')) {
        put('letterSpacing', s.slice('font-letter-spacing-'.length), name);
      }
    }
    for (const bucket of Object.keys(theme)) {
      if (Object.keys(theme[bucket]).length === 0) delete theme[bucket];
    }
    return (
      '/* Generated by build.mjs — do not edit. Eidra Tailwind v3 preset. */\n' +
      '/* Load @eidra/tokens/css (the CSS variables) for these utilities to resolve. */\n' +
      `module.exports = ${JSON.stringify({ theme: { extend: theme } }, null, 2)};\n`
    );
  },
});

// Tailwind v4 theme bridge — CSS-first. Tailwind v4 dropped JS preset configs
// (`presets: [...]`) in favour of a CSS `@theme`, so the v3 `.cjs` preset above is
// unusable in a v4 app; consumers were hand-maintaining the token→theme map in their
// own globals.css (and it silently drifted). This emits that map from the same token
// walk so it can't drift. Maps each --eidra-* token onto Tailwind v4's theme
// namespaces (--color-*, --spacing-*, --radius-*, --shadow-*, --font-*, --text-*,
// --font-weight-*, --leading-*, --tracking-*, --ease-*). `@theme inline` keeps the
// utilities referencing var(--eidra-*) so they stay theme-reactive (light/dark/finance).
StyleDictionary.registerFormat({
  name: 'eidra/tailwind-v4',
  format: ({ dictionary }) => {
    // bucket -> v4 theme namespace prefix
    const buckets = {
      color: [],
      spacing: [],
      radius: [],
      shadow: [],
      font: [],
      text: [],
      'font-weight': [],
      leading: [],
      tracking: [],
      ease: [],
    };
    const put = (bucket, key, name) =>
      buckets[bucket].push(`  --${bucket}-${key}: var(--${name});`);
    for (const t of dictionary.allTokens) {
      const name = t.name;
      const s = name.replace(/^eidra-/, '');
      if (typ(t) === 'color') {
        put('color', s.replace(/^color-/, ''), name);
      } else if (s.startsWith('space-')) {
        put('spacing', s.slice('space-'.length), name);
      } else if (s.startsWith('size-')) {
        put('spacing', s.slice('size-'.length), name);
      } else if (s.startsWith('radius-')) {
        put('radius', s.slice('radius-'.length), name);
      } else if (s.startsWith('shadow-')) {
        put('shadow', s.slice('shadow-'.length), name);
      } else if (s.startsWith('font-family-')) {
        put('font', s.slice('font-family-'.length), name);
      } else if (s.startsWith('font-size-')) {
        put('text', s.slice('font-size-'.length), name);
      } else if (s.startsWith('font-weight-')) {
        put('font-weight', s.slice('font-weight-'.length), name);
      } else if (s.startsWith('font-line-height-')) {
        put('leading', s.slice('font-line-height-'.length), name);
      } else if (s.startsWith('font-letter-spacing-')) {
        put('tracking', s.slice('font-letter-spacing-'.length), name);
      } else if (s.startsWith('easing-')) {
        put('ease', s.slice('easing-'.length), name);
      }
    }
    const body = Object.values(buckets)
      .filter((lines) => lines.length)
      .map((lines) => lines.join('\n'))
      .join('\n\n');
    return (
      '/* Generated by build.mjs — do not edit. Eidra Tailwind v4 theme bridge. */\n' +
      "/* Tailwind v4, CSS-first. Maps every --eidra-* token onto Tailwind's @theme so\n" +
      '   utilities resolve to var(--eidra-*) and stay theme-reactive (light/dark/finance).\n' +
      '   Import AFTER `@import "tailwindcss"` and the eidra token CSS variables:\n' +
      "     @import '@eidra/react/styles.css';\n" +
      "     @import 'tailwindcss';\n" +
      "     @import '@eidra/react/tailwind.css';\n" +
      "   This adds the Eidra tokens ALONGSIDE Tailwind's built-in theme. To generate\n" +
      "   ONLY Eidra utilities (drop Tailwind's defaults), additionally import the opt-in\n" +
      "   reset BEFORE this file: @import '@eidra/react/tailwind-reset.css'. */\n" +
      '@layer theme, base, components, utilities;\n\n' +
      `@theme inline {\n${body}\n}\n`
    );
  },
});

const cssPlatform = (files) => ({ transformGroup: 'eidra/css', buildPath: BUILD, files });

async function run() {
  await fs.mkdir(BUILD, { recursive: true });

  const light = new StyleDictionary({
    usesDtcg: true,
    source: ['tokens/primitives/**/*.json', 'tokens/semantic/light.json'],
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: {
      css: cssPlatform([
        {
          destination: 'primitives.css',
          format: 'css/variables',
          filter: (t) => !isSemantic(t),
          options: { selector: ':root', outputReferences: false },
        },
        {
          destination: 'light.css',
          format: 'css/variables',
          filter: isSemantic,
          options: { selector: ":root,\n[data-theme='light']", outputReferences: true },
        },
      ]),
      ts: {
        transformGroup: 'eidra/css',
        buildPath: BUILD,
        files: [{ destination: 'tokens.ts', format: 'eidra/ts' }],
      },
      tailwind: {
        transformGroup: 'eidra/css',
        buildPath: BUILD,
        files: [
          { destination: 'tailwind-preset.cjs', format: 'eidra/tailwind' },
          { destination: 'tailwind.css', format: 'eidra/tailwind-v4' },
        ],
      },
    },
  });
  await light.buildAllPlatforms();

  const dark = new StyleDictionary({
    usesDtcg: true,
    source: ['tokens/primitives/**/*.json', 'tokens/semantic/dark.json'],
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: {
      css: cssPlatform([
        {
          destination: 'dark.css',
          format: 'css/variables',
          filter: isSemantic,
          options: { selector: "[data-theme='dark']", outputReferences: true },
        },
      ]),
    },
  });
  await dark.buildAllPlatforms();

  const header = '/* Eidra Design System — generated tokens. Do not edit by hand. */\n';
  const read = (f) => fs.readFile(path.join(BUILD, f), 'utf8');
  const [prim, lightCss, darkCss] = await Promise.all([
    read('primitives.css'),
    read('light.css'),
    read('dark.css'),
  ]);

  // Vite builds with emptyOutDir:false (so it won't wipe these), so clean dist here.
  await fs.rm('dist', { recursive: true, force: true });
  await fs.mkdir('dist', { recursive: true });
  await fs.writeFile('dist/eidra-tokens.css', `${header}\n${prim}\n${lightCss}\n${darkCss}`);

  await fs.mkdir('src', { recursive: true });
  await fs.writeFile('src/_generated.ts', await read('tokens.ts'));

  // Tailwind preset for consuming apps (e.g. `presets: [require('@eidra/tokens/tailwind')]`).
  await fs.writeFile('dist/tailwind-preset.cjs', await read('tailwind-preset.cjs'));
  // Tailwind v4 theme bridge (`@import '@eidra/tokens/tailwind.css'`).
  await fs.writeFile('dist/tailwind.css', await read('tailwind.css'));
  // Opt-in Tailwind v4 reset (`@import '@eidra/tokens/tailwind-reset.css'`). Drops
  // Tailwind's built-in theme so only Eidra tokens generate utilities. Kept separate
  // from the bridge so the design system enables this rather than forcing it — import
  // it only if you want Eidra-only utilities. Must come AFTER `@import "tailwindcss"`
  // and BEFORE the bridge, so the reset clears defaults and the bridge re-adds Eidra.
  await fs.writeFile(
    'dist/tailwind-reset.css',
    '/* Generated by build.mjs — do not edit. Eidra Tailwind v4 reset (opt-in). */\n' +
      "/* Drops Tailwind's built-in theme so ONLY Eidra tokens generate utilities.\n" +
      '   Opt-in: import AFTER `@import "tailwindcss"` and BEFORE the bridge:\n' +
      "     @import 'tailwindcss';\n" +
      "     @import '@eidra/react/tailwind-reset.css';\n" +
      "     @import '@eidra/react/tailwind.css';\n" +
      "   Omit it to keep Tailwind's defaults alongside the Eidra utilities. */\n" +
      '@theme {\n  --*: initial;\n}\n',
  );

  // ship fonts alongside tokens
  await fs.copyFile('fonts.css', 'dist/fonts.css');
  try {
    await fs.cp('fonts', 'dist/fonts', { recursive: true });
  } catch {
    /* no font files yet — fonts.css falls back to the system stack */
  }

  console.log(
    '✓ @eidra/tokens: CSS + TS + Tailwind v3 preset + v4 theme bridge (+ opt-in reset) generated',
  );
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
