// Generates an agent-readable catalog of the component library from source, so it can
// never drift. Emits:
//   docs/COMPONENTS.md        — full catalog for humans + agents working in this repo
//   packages/react/llms.txt   — shipped inside @eidra/react (in `files`), so a consumer's
//                               agent finds it at node_modules/@eidra/react/llms.txt
import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const COMPONENTS_DIR = path.join(ROOT, 'packages/react/src/components');
const TOKENS_CSS = path.join(ROOT, 'packages/tokens/dist/eidra-tokens.css');

const read = (p) => fs.readFile(p, 'utf8').catch(() => '');

function jsdocFor(src, name) {
  // JSDoc block immediately preceding the main export of `name`.
  // A single JSDoc block (no nested `*/`) immediately attached to the export of `name`.
  const re = new RegExp(
    `/\\*\\*((?:(?!\\*/)[\\s\\S])*?)\\*/\\s*(?:export\\s+)?(?:const|function)\\s+${name}\\b`,
  );
  const m = src.match(re);
  if (!m) return '';
  return m[1]
    .split('\n')
    .map((l) => l.replace(/^\s*\*?\s?/, '').trim())
    .filter((l) => !l.startsWith('@') && !l.includes('```') && l !== '*')
    .join(' ')
    .split(/(?<=\.)\s/)[0]
    .trim();
}

function parts(src, name) {
  // Keys of a compound export: `export const Name = { A, B }` or `Object.assign(X, { A, B })`.
  const obj =
    src.match(new RegExp(`export const ${name}\\s*(?::[^=]+)?=\\s*\\{([\\s\\S]*?)\\}`)) ||
    src.match(new RegExp(`export const ${name}\\s*=\\s*Object\\.assign\\([^,]+,\\s*\\{([\\s\\S]*?)\\}`));
  if (!obj) return [];
  return [...obj[1].matchAll(/^\s*([A-Z][A-Za-z0-9]*)\s*[,:]/gm)].map((m) => m[1]);
}

function exportsFrom(indexSrc) {
  const values = [];
  const types = [];
  for (const m of indexSrc.matchAll(/export\s+(type\s+)?\{([^}]*)\}/g)) {
    const names = m[2]
      .split(',')
      .map((s) => s.trim().split(/\s+as\s+/).pop().trim())
      .filter(Boolean);
    (m[1] ? types : values).push(...names);
  }
  return { values, types };
}

async function tokenReference() {
  const css = await read(TOKENS_CSS);
  const names = [...new Set([...css.matchAll(/--eidra-[a-z0-9-]+/g)].map((m) => m[0]))];
  const bucket = (re) => names.filter((n) => re.test(n));
  const scale = (prefix) => {
    const all = bucket(new RegExp(`^--eidra-color-${prefix}-`));
    return all.length ? `${all[0]} … ${all[all.length - 1]} (${all.length} steps)` : '';
  };
  return [
    '### Tokens (use these exact CSS variable names; never invent tokens)',
    '',
    '**Semantic colors (theme-aware — prefer these):**',
    bucket(/^--eidra-(bg|surface|fg|border|accent|coral|focus|success|danger|warning|info)/)
      .join(' '),
    '',
    '**Primitive color scales:** ' +
      ['grey', 'orange', 'coral', 'green', 'blue', 'red'].map((p) => `${p} (${scale(p)})`).join(', '),
    '',
    '**Type:** ' + bucket(/^--eidra-font-/).join(' '),
    '',
    '**Space:** ' + bucket(/^--eidra-space-/).join(' '),
    '',
    '**Radius / size / shadow / motion / z:** ' +
      bucket(/^--eidra-(radius|size|shadow|duration|easing|z)-/).join(' '),
  ].join('\n');
}

const HEADER = `# Eidra Design System — component catalog

Auto-generated by \`scripts/catalog.mjs\` from source. Do not edit by hand.

React component library built on [Base UI](https://base-ui.com/) (headless, accessible primitives), styled with Eidra design tokens. Packages: \`@eidra/tokens\` (CSS variables), \`@eidra/icons\` (Lucide wrapper), \`@eidra/react\` (components).

## Using it

\`\`\`tsx
// Load once at the app root (e.g. Next.js layout):
import '@eidra/react/styles.css'        // tokens + reset + all component styles
import '@eidra/tokens/fonts.css'        // Eidra Sans @font-face (skip if you load the font yourself)

import { ThemeProvider, Button } from '@eidra/react'
import { Icon, ChevronDown } from '@eidra/icons'

// Establish the theme scope (or put class="eidra-root" data-theme="light" on your own root):
<ThemeProvider theme="light" density="comfortable">
  <Button tone="accent">Save</Button>
</ThemeProvider>
\`\`\`

- Theme: \`data-theme="light" | "dark"\` on the \`eidra-root\` element. Density: \`data-density="comfortable" | "compact"\`.
- Style with token CSS variables (e.g. \`var(--eidra-space-4)\`), not raw values.
- **Exact prop types for every component are in \`node_modules/@eidra/react/dist/index.d.ts\`.** This catalog is the index; the \`.d.ts\` is the source of truth for props.
- Compound components are namespaces: render the listed parts (e.g. \`<Dialog.Root><Dialog.Trigger/>…</Dialog.Root>\`).
- \`@eidra/react\` is a client boundary (\`"use client"\` baked in) — safe to import from React Server Components.
`;

async function main() {
  const dirs = (await fs.readdir(COMPONENTS_DIR, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const entries = [];
  for (const name of dirs) {
    const dir = path.join(COMPONENTS_DIR, name);
    const indexSrc = await read(path.join(dir, 'index.ts'));
    const mainSrc = await read(path.join(dir, `${name}.tsx`));
    const storySrc = await read(path.join(dir, `${name}.stories.tsx`));
    const { values, types } = exportsFrom(indexSrc);
    const main = values[0] ?? name;
    entries.push({
      name,
      category: (storySrc.match(/title:\s*['"]([^'"/]+)\//) ?? [])[1] ?? 'Components',
      description: jsdocFor(mainSrc, main) || jsdocFor(mainSrc, name),
      values,
      types,
      parts: parts(mainSrc, main),
    });
  }

  const byCategory = {};
  for (const e of entries) (byCategory[e.category] ??= []).push(e);

  const sections = Object.keys(byCategory)
    .sort()
    .map((cat) => {
      const rows = byCategory[cat]
        .map((e) => {
          const imp = e.values.join(', ');
          const partsStr = e.parts.length ? ` · parts: ${e.parts.map((p) => `${e.name}.${p}`).join(', ')}` : '';
          const desc = e.description ? ` — ${e.description}` : '';
          return `- **${e.name}**${desc}\n  - import: \`import { ${imp} } from '@eidra/react'\`${partsStr}`;
        })
        .join('\n');
      return `### ${cat}\n\n${rows}`;
    })
    .join('\n\n');

  const tokens = await tokenReference();
  const body = `${HEADER}\n## Components (${entries.length})\n\n${sections}\n\n${tokens}\n`;

  await fs.writeFile(path.join(ROOT, 'docs/COMPONENTS.md'), body);
  await fs.writeFile(path.join(ROOT, 'packages/react/llms.txt'), body);
  console.log(`✓ catalog: ${entries.length} components → docs/COMPONENTS.md + packages/react/llms.txt`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
